#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPBarcodeResponse.h"


@protocol ASPBarcodeResponseList
@end

@interface ASPBarcodeResponseList : ASPObject


@property(nonatomic) NSArray<ASPBarcodeResponse>* barcodes;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
