#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPBarcodeResponse
@end

@interface ASPBarcodeResponse : ASPObject


@property(nonatomic) NSString* barcodeValue;

@property(nonatomic) NSString* barcodeType;

@property(nonatomic) NSArray* /* NSString */ region;

@property(nonatomic) NSString* checksum;

@end
