#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPResolution.h"
#import "ASPMargins.h"


@protocol ASPBarcodeBuilder
@end

@interface ASPBarcodeBuilder : ASPObject


@property(nonatomic) NSString* typeOfBarcode;

@property(nonatomic) NSString* text;

@property(nonatomic) ASPResolution* resolution;

@property(nonatomic) NSNumber* dimensionX;

@property(nonatomic) NSNumber* dimensionY;

@property(nonatomic) NSString* codeLocation;

@property(nonatomic) NSString* graphicsUnit;

@property(nonatomic) NSNumber* autoSize;

@property(nonatomic) NSNumber* barHeight;

@property(nonatomic) NSNumber* imageHeight;

@property(nonatomic) NSNumber* imageWidth;

@property(nonatomic) NSString* imageQuality;

@property(nonatomic) NSNumber* rotationAngle;

@property(nonatomic) ASPMargins* margins;

@property(nonatomic) NSString* backColor;

@property(nonatomic) NSString* foreColor;

@property(nonatomic) NSString* codeTextColor;

@property(nonatomic) NSString* borderColor;

@property(nonatomic) NSNumber* borderVisible;

@property(nonatomic) NSString* enableChecksum;

@end
