#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPBarcodeReader
@end

@interface ASPBarcodeReader : ASPObject


@property(nonatomic) NSString* checksumValidation;

@property(nonatomic) NSNumber* stripFNC;

@property(nonatomic) NSNumber* barcodesCount;

@property(nonatomic) NSNumber* rotationAngle;

@property(nonatomic) NSString* binarizationHints;

@end
