<?php
namespace Aspose\Barcode\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class BarcodeReader {
	static $swaggerTypes = array(
		'ChecksumValidation' => 'ChecksumValidation',
		'StripFNC' => 'bool',
		'BarcodesCount' => 'int',
		'RotationAngle' => 'int',
		'BinarizationHints' => 'BinarizationHints'

	);

	public $ChecksumValidation; // ChecksumValidation
	public $StripFNC; // bool
	public $BarcodesCount; // int
	public $RotationAngle; // int
	public $BinarizationHints; // BinarizationHints
	}

